import type { FoodListing, UserProfile } from "../types";

export const mockUser: UserProfile = {
  id: "1",
  name: "Alex Johnson",
  email: "alex@umich.edu",
  phone: "(734) 555-0123",
  zip_code: "48104",
  avatar_url: undefined,
  points: 235,
  pickups: 12,
  lbs_saved: 18,
  high_contrast: false,
  created_at: "2024-01-15T00:00:00Z",
};

export const mockListings: FoodListing[] = [
  {
    id: "1",
    title: "Fresh Produce & Bread",
    description:
      "Assorted vegetables from farmers market, whole wheat bread, apples. All fresh from today!",
    food_type: "produce",
    emoji: "🥬",
    location_name: "Main Library",
    distance: "2 blocks away",
    accessibility_tags: ["wheelchair", "covered", "parking"],
    available_from: "2024-03-08T10:00:00Z",
    available_until: "2024-03-08T11:00:00Z",
    minutes_remaining: 30,
    poster_id: "2",
    poster_name: "Maria G.",
    status: "available",
    created_at: "2024-03-08T09:30:00Z",
  },
  {
    id: "2",
    title: "Homemade Pasta & Sauce",
    description:
      "Fresh homemade fettuccine with marinara sauce. Made this morning, enough for 4 servings.",
    food_type: "prepared",
    emoji: "🍕",
    location_name: "Student Union",
    distance: "5 blocks away",
    accessibility_tags: ["wheelchair", "transit"],
    available_from: "2024-03-08T11:00:00Z",
    available_until: "2024-03-08T14:00:00Z",
    minutes_remaining: 120,
    poster_id: "3",
    poster_name: "David L.",
    status: "available",
    created_at: "2024-03-08T10:00:00Z",
  },
  {
    id: "3",
    title: "Bakery Overflow",
    description:
      "Croissants, sourdough loaves, and cinnamon rolls from this morning. Still warm!",
    food_type: "baked",
    emoji: "🥖",
    location_name: "Central Campus",
    distance: "3 blocks away",
    accessibility_tags: ["parking", "covered"],
    available_from: "2024-03-08T08:00:00Z",
    available_until: "2024-03-08T10:30:00Z",
    minutes_remaining: 45,
    poster_id: "4",
    poster_name: "Sarah K.",
    status: "available",
    created_at: "2024-03-08T07:30:00Z",
  },
  {
    id: "4",
    title: "Canned Goods Bundle",
    description:
      "Assorted canned vegetables, beans, and soups. All unexpired, mostly organic brands.",
    food_type: "packaged",
    emoji: "🥫",
    location_name: "North Campus",
    distance: "1 mile away",
    accessibility_tags: ["parking", "transit"],
    available_from: "2024-03-08T09:00:00Z",
    available_until: "2024-03-08T18:00:00Z",
    minutes_remaining: 360,
    poster_id: "5",
    poster_name: "James T.",
    status: "available",
    created_at: "2024-03-08T08:00:00Z",
  },
];
